dblapi: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc0MDExMjM1MzQ4MzU1NDg1OCIsImJvdCI6dHJ1ZSwiaWF0IjoxNjA1NDk5OTc3fQ.0S6h9gpQg77c0mLRqLC4vc4zgduENIBrPlXzkRtDF24
boatsapi: 2bo3CkMT7P6CNxx7IBQrO5haxlOsSPazT8ExCCKAvUVxzuW8bKlsJqw3JH6yDd40B39zmNIGS4uV4SgVY3w54fIaiRiA0mJkMzlNlkCFCKvxoL4mtI1ABWvRfmpnUDrj8RutB2rjA7Uv9rVp9k9wt4G9VCr
alexapi: 93jQYsGpTm_Jz44_fxV2VlsL9t6Uk36zfHq3buCb
ytapi: AIzaSyAeoZxsotVd1HdcqG8KXAIzS_O8FxQbel0
spcid: c74bc6e28b154643b5b1f1f51c21fdfb
spcs: ec94116a9a2c4212936afc33f55b697b
sessionid: 14643228375%3AwtGbRlhe4qGtU8%3A9
nodes:
  - auth: youshallnotpass
    url: node-au.rahagia.tech:3002
    name: rahagia
  - auth: LoliBandarHunter
    url: node-au.fab1o.xyz:2333
    name: fabio
devMode: false
devGuild:
  - "770540956163899423"
  - "785715968608567297"
  - "332877090003091456"
