name: Lint & Compile Test

on:
    push:
        paths:
            - "**.ts"
            - "package.json",
            - "test.yml"
        branches:
            - master
    pull_request:
        paths:
            - "**.ts"
            - "package.json",
            - "test.yml"
        branches:
            - "**"

jobs:
    lint:
        name: ESLint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - ">=16.x <17.x"
        steps:
            - name: Checkout repository
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: true

            - name: Install dependencies
              run: npm i

            - name: Run ESLint
              run: npm run lint

    compile:
        needs: lint
        name: Compile
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - ">=16.x <17.x"
        steps:
            - name: Checkout repository
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3.2.0
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: true

            - name: Install dependencies
              run: npm i

            - name: Run Compile
              run: npm run build && rm -rf dist
